### ISSUE TITLE
Help to understand you EPD library

### ISSUE THREAD

**Issue by bestbug456** [itterheim/Go-RaspberryPi-Covid-19#1]
Hello,

I just bought a waveshare e-paper 2.13 like the one you show in photo and I was searching for usable library ready to use and I land here, I've a problem and maybe you can help me to figure out what I'm doing wrong. At the moment my code is basically a strip of what you have done since I was interested to have a "base" to start with my experiment:

```
        e := CreateEpd()
	defer e.Close()
	e.Init()
	// e.Clear()

	dest := draw()

	draw2dimg.SaveToPngFile("test.png", dest)

	data := getBuffer(dest)
	fmt.Println(data[:1])
	fmt.Printf("Display black\n")
	e.DisplayBlack(data)
	fmt.Printf("sleeping\n")
	e.Sleep()
```

But the system remain stuck on the init phase on the check if e-Paper is busy. Reading the code I notice that the busy check is done after you send the command 0x04 (POWER_ON). I went on waveshare python example here
https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13_V2.py#L123

The readybusy check is done on different command, I try to move the check at the end of the init and in this case the init procedure finish with success but no image is show on the e-paper, so clearly I'm missing something. Can you maybe help a complete newbie of the gpio world to understand what I'm doing wrong? If I use the python example of the waweshare I was able to send a test image but I prefer to use GO since the program I want to display on it is write in Golang.

Thanks in advance!

**Comment by itterheim** [comment]
Hi,
Firstly, I own [2.13" HAT B black/red/white display](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(B)) and my library is based on [epd2in13bc.py](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13bc.py)

I looked into the code for [2.13 HAT black/white display](https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT) and there seems to be a significant difference in the init sequence between the older version, which is similar to mine 2.13" HAT B, and the newer V2 version:
https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13.py#L97
https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13_V2.py#L123

I think that my code will mostly not be usable for you, as it's written for the older version.

However, here's how I rewrote `epd2in13bc.py` from python to Go.
1) I wrote a simple program in python using the official library. I was rendering two rectangles, just so I can test that it works and to find out which GPIO and SPI pins are used.

2) Then I rewrote it into GO, including the epd2in13bc.py. Mine [epd.go](https://github.com/itterheim/Go-RaspberryPi-Covid-19/blob/master/epd/epd.go) is basically complete copy of [epd2in13bc.py](https://github.com/waveshare/e-Paper/blob/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in13bc.py)

3) The hardest part was to find a suitable libraries for GPIO control and SPI communication. In the end, I used libraries from https://periph.io/

You might be able to use the first part of my `epd.go`, which takes care of initializing GPIO pins and opening SPI communication. (`Epd struct`, and functions `CreateEpd`, `Close`, `reset`, `sendCommand`, `sendData`, `readBusy`).
Then you'll probably have to translate the rest of the `epd2in13_V2.py` from python to Go, because it's too different from mine version.

```go
package epd

import (
	"fmt"
	"time"

	"periph.io/x/periph/conn/gpio"
	"periph.io/x/periph/conn/gpio/gpioreg"
	"periph.io/x/periph/conn/physic"
	"periph.io/x/periph/conn/spi"
	"periph.io/x/periph/conn/spi/spireg"
	"periph.io/x/periph/host"
)

// Epd is basic struc for Waveshare eps2in13bc
type Epd struct {
	width   int
	height  int
	port    spi.PortCloser
	spiConn spi.Conn
	rstPin  gpio.PinIO
	dcPin   gpio.PinIO
	csPin   gpio.PinIO
	busyPin gpio.PinIO
}

// CreateEpd is constructor for Epd
func CreateEpd() Epd {
	e := Epd{
		width:  104,
		height: 212,
	}

	var err error

	host.Init()

	// SPI
	e.port, err = spireg.Open("")
	if err != nil {
		fmt.Println(err)
	}

	e.spiConn, err = e.port.Connect(2*physic.MegaHertz, spi.Mode0, 8)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(e.spiConn)

	// GPIO - read
	e.rstPin = gpioreg.ByName("GPIO17")  // out
	e.dcPin = gpioreg.ByName("GPIO25")   // out
	e.csPin = gpioreg.ByName("GPIO8")    // out
	e.busyPin = gpioreg.ByName("GPIO24") // in

	return e
}

// Close is closing pariph.io port
func (e *Epd) Close() {
	e.port.Close()
}

// reset epd
func (e *Epd) reset() {
	e.rstPin.Out(true)
	time.Sleep(200 * time.Millisecond)
	e.rstPin.Out(false)
	time.Sleep(10 * time.Millisecond)
	e.rstPin.Out(true)
	time.Sleep(200 * time.Millisecond)
}

// sendCommand sets DC ping low and sends byte over SPI
func (e *Epd) sendCommand(command byte) {
	e.dcPin.Out(false)
	e.csPin.Out(false)
	c := []byte{command}
	r := make([]byte, len(c))
	e.spiConn.Tx(c, r)
	e.csPin.Out(true)
}

// sendData sets DC ping high and sends byte over SPI
func (e *Epd) sendData(data byte) {
	e.dcPin.Out(true)
	e.csPin.Out(false)
	c := []byte{data}
	r := make([]byte, len(c))
	e.spiConn.Tx(c, r)
	e.csPin.Out(true)
}

// ReadBusy waits for epd
func (e *Epd) readBusy() {
	fmt.Println("e-Paper busy")
	// Low for busy
	for e.busyPin.Read() == gpio.Low {
		time.Sleep(100 * time.Millisecond)
	}
	fmt.Println("e-Paper busy release")
}

// ...
```

**Comment by bestbug456** [comment]
Hi thanks a lot for the response! Have a nice day!
